name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, dom, curl, zip, gd, mysqlnd, bcmath, soap, intl

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs

      # Deploy Project Root (semua file kecuali public)
      - name: Deploy Laravel Root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /elnair/
          local-dir: ./
          protocol: ftps
          port: 21
          dangerous-clean-slate: true
          exclude: |
            public/**
            **/.git*
            **/.env
            **/node_modules/**
            **/storage/framework/cache/*
            **/storage/framework/sessions/*
            **/storage/framework/views/*
            **/storage/logs/*
            .github

      # Deploy Public Folder
      - name: Deploy Public Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/elnair/
          local-dir: ./public
          protocol: ftps
          port: 21
          dangerous-clean-slate: true