name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, dom, curl, zip, gd, mysqlnd, bcmath, soap, intl

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Deploy Laravel Project
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git/**
            **/.git*
            **/node_modules/**
            **/.github/**
            **/.env
            **/.env.*
            **/public/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            .editorconfig
            README.md

      - name: Deploy Public Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./public/
          server-dir: ../public_html/elnair/
          exclude: |
            **/.DS_Store